name: Deploy to cPanel

on:
  push:
    branches:
      - main  # আপনার ব্রাঞ্চের নাম main নাকি master তা নিশ্চিত হয়ে নিন

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files via SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDZz --delete"
          SERVER_PORT: "22"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: "/home/sites/32a/a/ae27c3a9d7/www.withbd.com/rongin"